### ISSUE TITLE
SongService dependency not getting resolved by IoC

### ISSUE THREAD

**Issue by Suzii** [Suzii/pa165-music-library#4]
In class SongService there is a dependency on other class from same package that does not get resolved by Spring IoC : AlbumService. This dependency was added later as part of refactoring first free position in album function and appears not working correctly. Temporary fix was introduced, although it is important to resolve initial problem.

**Comment by xstefank** [comment]
232174e3f9322d6077bc2e5dd094d6cf5ecb9683
